# Build Stage
FROM golang:1.15 AS build-stage

ADD . /opt/kubevirt
WORKDIR /opt/kubevirt

RUN mkdir bin && GOPROXY=goproxy.cn go build -o ./bin/ -mod vendor cmd/virt-api/virt-api.go


## Final Stage
FROM kubevirt/virt-api:v0.36.0

COPY --from=build-stage  /opt/kubevirt/bin/virt-api /usr/bin
