# Build Stage
FROM golang:1.15 AS build-stage

ADD . /opt/kubevirt
WORKDIR /opt/kubevirt

RUN mkdir bin && GOPROXY=goproxy.cn go build -o ./bin/ -mod vendor cmd/virt-handler/virt-handler.go


## Final Stage
FROM kubevirt/virt-handler:v0.36.0

COPY --from=build-stage  /opt/kubevirt/bin/virt-handler /usr/bin
