name: Go

on:
  push:
    branches: [ release-0.36 ]
  pull_request:
    branches: [ release-0.36 ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: release-0.36
    - name: SSH connection to Actions
      uses: P3TERX/ssh2actions@v1.0.0
